version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env

  test:
    image: postgres:latest
    restart: always
    container_name: test
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    command: postgres --listen_addresses=*
    volumes:
      - db-data:/var/lib/postgresql/data/

  api:
    build:
      context: .
    command: ["/code/docker/app.sh"]
    container_name: api
    depends_on:
      - postgres
      - test
    env_file:
      - .env
    ports:
      - "8070:8000"
volumes:
  db-data: