version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres
    ports:
      - "80:80"
      - "5432:5432"
    env_file:
      - .env
  
  backend:
    
