"""empty message

Revision ID: 7bf4812d7c93
Revises: a1c0e7e3b5f1
Create Date: 2024-01-17 21:57:53.956905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bf4812d7c93'
down_revision: Union[str, None] = 'a1c0e7e3b5f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight-history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_weight-history_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weight-history'))
    )
    op.drop_table('weigh-history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weigh-history',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"weigh-history_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('weigh', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_weigh-history_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_weigh-history')
    )
    op.drop_table('weight-history')
    # ### end Alembic commands ###
